#!/usr/bin/env bash
# Standalone sync launcher — works even if the bootstrap repo is deleted locally.
# Clones or pulls the bootstrap repo, then delegates to its sync.sh.
# Generated by setup.sh — do not edit manually.

set -e

BOOTSTRAP_DIR="__BOOTSTRAP_DIR__"
BOOTSTRAP_REPO="__BOOTSTRAP_REPO__"
AI_BASE="$(cd "$(dirname "$0")" && pwd)"

# Read repo URL and dir from marker if available (supports forks or moved dirs)
MARKER="$AI_BASE/__YOURNAME__/.bootstrap-source"
if [ -f "$MARKER" ]; then
  STORED_REPO=$(grep '^repo=' "$MARKER" | cut -d= -f2-)
  STORED_DIR=$(grep '^bootstrap_dir=' "$MARKER" | cut -d= -f2-)
  [ -n "$STORED_REPO" ] && BOOTSTRAP_REPO="$STORED_REPO"
  [ -n "$STORED_DIR" ] && BOOTSTRAP_DIR="$STORED_DIR"
fi

echo ""
if [ ! -d "$BOOTSTRAP_DIR/.git" ]; then
  echo "Bootstrap repo not found locally. Cloning from $BOOTSTRAP_REPO ..."
  git clone "$BOOTSTRAP_REPO" "$BOOTSTRAP_DIR"
else
  echo "Pulling latest bootstrap..."
  git -C "$BOOTSTRAP_DIR" pull origin main --quiet
fi

exec "$BOOTSTRAP_DIR/sync.sh" "$@"
